//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.SOAPService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAPService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        MVC.SOAPService.CompositeType GetDataUsingDataContract(MVC.SOAPService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MVC.SOAPService.CompositeType> GetDataUsingDataContractAsync(MVC.SOAPService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMovies", ReplyAction="http://tempuri.org/IService1/GetMoviesResponse")]
        ApplicationService.DTOs.MovieDTO[] GetMovies(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMovies", ReplyAction="http://tempuri.org/IService1/GetMoviesResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.MovieDTO[]> GetMoviesAsync(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMovieByID", ReplyAction="http://tempuri.org/IService1/GetMovieByIDResponse")]
        ApplicationService.DTOs.MovieDTO GetMovieByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMovieByID", ReplyAction="http://tempuri.org/IService1/GetMovieByIDResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.MovieDTO> GetMovieByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutMovie", ReplyAction="http://tempuri.org/IService1/PutMovieResponse")]
        string PutMovie(ApplicationService.DTOs.MovieDTO movieDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutMovie", ReplyAction="http://tempuri.org/IService1/PutMovieResponse")]
        System.Threading.Tasks.Task<string> PutMovieAsync(ApplicationService.DTOs.MovieDTO movieDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostMovie", ReplyAction="http://tempuri.org/IService1/PostMovieResponse")]
        string PostMovie(ApplicationService.DTOs.MovieDTO movieDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostMovie", ReplyAction="http://tempuri.org/IService1/PostMovieResponse")]
        System.Threading.Tasks.Task<string> PostMovieAsync(ApplicationService.DTOs.MovieDTO movieDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMovie", ReplyAction="http://tempuri.org/IService1/DeleteMovieResponse")]
        string DeleteMovie(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMovie", ReplyAction="http://tempuri.org/IService1/DeleteMovieResponse")]
        System.Threading.Tasks.Task<string> DeleteMovieAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsers", ReplyAction="http://tempuri.org/IService1/GetUsersResponse")]
        ApplicationService.DTOs.UserDTO[] GetUsers(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsers", ReplyAction="http://tempuri.org/IService1/GetUsersResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.UserDTO[]> GetUsersAsync(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserByID", ReplyAction="http://tempuri.org/IService1/GetUserByIDResponse")]
        ApplicationService.DTOs.UserDTO GetUserByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserByID", ReplyAction="http://tempuri.org/IService1/GetUserByIDResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.UserDTO> GetUserByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutUser", ReplyAction="http://tempuri.org/IService1/PutUserResponse")]
        string PutUser(ApplicationService.DTOs.UserDTO userDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutUser", ReplyAction="http://tempuri.org/IService1/PutUserResponse")]
        System.Threading.Tasks.Task<string> PutUserAsync(ApplicationService.DTOs.UserDTO userDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostUser", ReplyAction="http://tempuri.org/IService1/PostUserResponse")]
        string PostUser(ApplicationService.DTOs.UserDTO userDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostUser", ReplyAction="http://tempuri.org/IService1/PostUserResponse")]
        System.Threading.Tasks.Task<string> PostUserAsync(ApplicationService.DTOs.UserDTO userDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        string DeleteUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        System.Threading.Tasks.Task<string> DeleteUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserMovies", ReplyAction="http://tempuri.org/IService1/GetUserMoviesResponse")]
        ApplicationService.DTOs.UserMovieDTO[] GetUserMovies(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserMovies", ReplyAction="http://tempuri.org/IService1/GetUserMoviesResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.UserMovieDTO[]> GetUserMoviesAsync(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserMovieById", ReplyAction="http://tempuri.org/IService1/GetUserMovieByIdResponse")]
        ApplicationService.DTOs.UserMovieDTO GetUserMovieById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserMovieById", ReplyAction="http://tempuri.org/IService1/GetUserMovieByIdResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.UserMovieDTO> GetUserMovieByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutUserMovie", ReplyAction="http://tempuri.org/IService1/PutUserMovieResponse")]
        string PutUserMovie(ApplicationService.DTOs.UserMovieDTO userMovieDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutUserMovie", ReplyAction="http://tempuri.org/IService1/PutUserMovieResponse")]
        System.Threading.Tasks.Task<string> PutUserMovieAsync(ApplicationService.DTOs.UserMovieDTO userMovieDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostUserMovie", ReplyAction="http://tempuri.org/IService1/PostUserMovieResponse")]
        string PostUserMovie(ApplicationService.DTOs.UserMovieDTO userMovieDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostUserMovie", ReplyAction="http://tempuri.org/IService1/PostUserMovieResponse")]
        System.Threading.Tasks.Task<string> PostUserMovieAsync(ApplicationService.DTOs.UserMovieDTO userMovieDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUserMovie", ReplyAction="http://tempuri.org/IService1/DeleteUserMovieResponse")]
        string DeleteUserMovie(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUserMovie", ReplyAction="http://tempuri.org/IService1/DeleteUserMovieResponse")]
        System.Threading.Tasks.Task<string> DeleteUserMovieAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MVC.SOAPService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MVC.SOAPService.IService1>, MVC.SOAPService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public MVC.SOAPService.CompositeType GetDataUsingDataContract(MVC.SOAPService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<MVC.SOAPService.CompositeType> GetDataUsingDataContractAsync(MVC.SOAPService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public ApplicationService.DTOs.MovieDTO[] GetMovies(string filter) {
            return base.Channel.GetMovies(filter);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.MovieDTO[]> GetMoviesAsync(string filter) {
            return base.Channel.GetMoviesAsync(filter);
        }
        
        public ApplicationService.DTOs.MovieDTO GetMovieByID(int id) {
            return base.Channel.GetMovieByID(id);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.MovieDTO> GetMovieByIDAsync(int id) {
            return base.Channel.GetMovieByIDAsync(id);
        }
        
        public string PutMovie(ApplicationService.DTOs.MovieDTO movieDto) {
            return base.Channel.PutMovie(movieDto);
        }
        
        public System.Threading.Tasks.Task<string> PutMovieAsync(ApplicationService.DTOs.MovieDTO movieDto) {
            return base.Channel.PutMovieAsync(movieDto);
        }
        
        public string PostMovie(ApplicationService.DTOs.MovieDTO movieDto) {
            return base.Channel.PostMovie(movieDto);
        }
        
        public System.Threading.Tasks.Task<string> PostMovieAsync(ApplicationService.DTOs.MovieDTO movieDto) {
            return base.Channel.PostMovieAsync(movieDto);
        }
        
        public string DeleteMovie(int id) {
            return base.Channel.DeleteMovie(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteMovieAsync(int id) {
            return base.Channel.DeleteMovieAsync(id);
        }
        
        public ApplicationService.DTOs.UserDTO[] GetUsers(string search) {
            return base.Channel.GetUsers(search);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.UserDTO[]> GetUsersAsync(string search) {
            return base.Channel.GetUsersAsync(search);
        }
        
        public ApplicationService.DTOs.UserDTO GetUserByID(int id) {
            return base.Channel.GetUserByID(id);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.UserDTO> GetUserByIDAsync(int id) {
            return base.Channel.GetUserByIDAsync(id);
        }
        
        public string PutUser(ApplicationService.DTOs.UserDTO userDto) {
            return base.Channel.PutUser(userDto);
        }
        
        public System.Threading.Tasks.Task<string> PutUserAsync(ApplicationService.DTOs.UserDTO userDto) {
            return base.Channel.PutUserAsync(userDto);
        }
        
        public string PostUser(ApplicationService.DTOs.UserDTO userDto) {
            return base.Channel.PostUser(userDto);
        }
        
        public System.Threading.Tasks.Task<string> PostUserAsync(ApplicationService.DTOs.UserDTO userDto) {
            return base.Channel.PostUserAsync(userDto);
        }
        
        public string DeleteUser(int id) {
            return base.Channel.DeleteUser(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteUserAsync(int id) {
            return base.Channel.DeleteUserAsync(id);
        }
        
        public ApplicationService.DTOs.UserMovieDTO[] GetUserMovies(string filter) {
            return base.Channel.GetUserMovies(filter);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.UserMovieDTO[]> GetUserMoviesAsync(string filter) {
            return base.Channel.GetUserMoviesAsync(filter);
        }
        
        public ApplicationService.DTOs.UserMovieDTO GetUserMovieById(int id) {
            return base.Channel.GetUserMovieById(id);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.UserMovieDTO> GetUserMovieByIdAsync(int id) {
            return base.Channel.GetUserMovieByIdAsync(id);
        }
        
        public string PutUserMovie(ApplicationService.DTOs.UserMovieDTO userMovieDto) {
            return base.Channel.PutUserMovie(userMovieDto);
        }
        
        public System.Threading.Tasks.Task<string> PutUserMovieAsync(ApplicationService.DTOs.UserMovieDTO userMovieDto) {
            return base.Channel.PutUserMovieAsync(userMovieDto);
        }
        
        public string PostUserMovie(ApplicationService.DTOs.UserMovieDTO userMovieDto) {
            return base.Channel.PostUserMovie(userMovieDto);
        }
        
        public System.Threading.Tasks.Task<string> PostUserMovieAsync(ApplicationService.DTOs.UserMovieDTO userMovieDto) {
            return base.Channel.PostUserMovieAsync(userMovieDto);
        }
        
        public string DeleteUserMovie(int id) {
            return base.Channel.DeleteUserMovie(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteUserMovieAsync(int id) {
            return base.Channel.DeleteUserMovieAsync(id);
        }
    }
}
